version: '3.8'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: main
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    environment:
      REDIS_PASSWORD: 1234
    ports:
      - "6379:6379"
